# Use Nginx as the base image to serve the React app
FROM nginx:alpine

# Copy the build output to the Nginx web server directory
COPY build /usr/share/nginx/html

# Expose port 80 to allow access
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
